version: '3.7'

services:
  app:
    platform: linux/amd64
    container_name: open-city-profile-ui
    build:
      context: .
      target: ${DOCKER_TARGET:-development}
    env_file:
      - .env
      - .env.development
      - .env.local
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
