name: Automated Tests and Linting

on:
  push:
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14.19.1'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install packages
        run: yarn install

      - name: Run code linting
        run: yarn lint

      - name: Run test
        run: yarn ci

      - name: Publish code coverage
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage/lcov.info
          fail_ci_if_error: true

      - name: Build
        run: yarn build
        if: github.event_name == 'pull_request' && (github.event.pull_request.base.ref == 'master' || github.event.pull_request.base.ref == 'develop')
